# Generated by Django 5.0.4 on 2024-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_image_image_file_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("انیمه", "انیمه"), ("سریال", "سریال"), ("متفرقه", "متفرقه")],
                default="متفرقه",
                max_length=20,
            ),
        ),
    ]
