# Generated by Django 5.0.4 on 2024-07-23 12:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[200, 300],
                upload_to="post_images/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                null=True,
                quality=70,
                scale=None,
                size=[200, 200],
                upload_to="profile_images/",
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
